### ISSUE TITLE
Optional arguments

### ISSUE THREAD

**Issue by jgraef** [nimiq/jsonrpc#1]
Add support for optional arguments. We can either somehow interpret `Option<T>` arguments as optional or maybe add an attribute `#[default]` to tell the dispatcher-derive to use `unwrap_or_default` for this argument.

**Comment by sisou** [comment]
Additionally, when all arguments are optional (or the method doesn't take any arguments), the JSON-RPC spec says that [the `params` property in the request object _MAY_ also be omitted](https://www.jsonrpc.org/specification#request_object). This is currently not supported by this lib either.

**Comment by jsdanielh** [comment]
Resolved in #42.

**Comment by sisou** [comment]
Not resolved. Users still need to send `null` for all optional parameters. That is what the issue is originally about.

My change in #42 just allows omitting the `params` completely, not individual arguments.

**Comment by jsdanielh** [comment]
My bad, re-opening issue
